spring.application.name=COMP9034-Farm Project Management
server.port=8088

# Database config
# Database URL for MariaDB
spring.datasource.url=jdbc:mariadb://no1v0x.h.filess.io:3305/COMP9034_promisedor
# Database credentials
spring.datasource.username=COMP9034_promisedor
spring.datasource.password=MinhQuan1608!
# MariaDB JDBC driver class
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDB106Dialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web.cors=DEBUG

#mail service
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000