# Database config
# Database URL for MariaDB
spring.datasource.url=jdbc:mariadb://no1v0x.h.filess.io:3305/COMP9034_promisedor
# Database credentials
spring.datasource.username=COMP9034_promisedor
spring.datasource.password=MinhQuan1608!

#mail service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=austindtg68@gmail.com
spring.mail.password=lnhg jxtq donk gpuo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000