# Database config
# Database URL for MariaDB
spring.datasource.url=jdbc:mariadb://no1v0x.h.filess.io:3305/COMP9034_promisedor
# Database credentials
spring.datasource.username=COMP9034_promisedor
spring.datasource.password=MinhQuan1608!
spring.jpa.hibernate.ddl-auto=validate