# Database config
# Database URL for MariaDB
spring.datasource.url=jdbc:mariadb://no1v0x.h.filess.io:3305/COMP9034_promisedor
# Database credentials
spring.datasource.username=COMP9034_promisedor
spring.datasource.password=MinhQuan1608!
# MariaDB JDBC driver class
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate Configuration for Testing
spring.jpa.database-platform=org.hibernate.dialect.MariaDB106Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web.cors=DEBUG

# Logging Configuration for Tests
logging.level.com.example.comp9034=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Test-specific configurations
spring.profiles.active=test