spring.application.name=COMP9034-Farm Project Management
server.port=8088
server.servlet.context-path=/The-Project

# Database config
# Database URL for MariaDB
spring.datasource.url=jdbc:mariadb://no1v0x.h.filess.io:3305/COMP9034_promisedor
# Database credentials
spring.datasource.username=COMP9034_promisedor
spring.datasource.password=MinhQuan1608!
# MariaDB JDBC driver class
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDB106Dialect