name: Backend Workflow (CI/CD)
on:
  push:
    branches: [main,test,dev]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [main,test,dev]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  syntax-check:
    name: Syntax check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend 
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Compile
        run: mvn -B -ntp -DskipTests compile
  docker-build:
    name: Docker build
    if: ${{ github.event_name == 'push'}}
    needs: [syntax-check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      environment: ${{ steps.generateglobaltag.outputs.environment }}
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate Tags
        id: generatetag
        shell: bash
        env:
          IMAGE_REGISTRY: ghcr.io/${{ github.repository }}/backend
          BRANCH: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
        run: |
          tags=("${IMAGE_REGISTRY}:${BRANCH}" "${IMAGE_REGISTRY}:${SHA}")
          if [ "$BRANCH" = "main" ]; then
            tags=("${IMAGE_REGISTRY}:latest" "${tags[@]}")
          fi
          {
            echo "tags<<EOF"
            printf "%s\n" "${tags[@]}"
            echo "EOF" 
          } >> $GITHUB_OUTPUT

      - name: Docker Information
        id: generateglobaltag
        run: |
          environment="${{ github.ref_name }}"
          if [ "${{ github.ref_name }}" = "main" ]; then
            environment="prod"
          fi
          echo "environment=$environment" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.generatetag.outputs.tags }}
          # build-args: |
          #   MODE=${{ steps.generateglobaltag.outputs.environment }}
  
  docker-deploy:
    name: Docker deploy
    needs: [syntax-check, docker-build]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ${{ needs.docker-build.outputs.environment }}
    steps:
      - name: Variable from docker build
        run: |
          echo "environment: ${{ needs.docker-build.outputs.environment }}"

      - name: Add droplet to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.DO_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd /opt/app

            # pull and restart service
            docker compose --profile backend_${{ needs.docker-build.outputs.environment }} up -d --pull always --no-deps

            # clean
            docker image prune -f